author: Derek M. Frank
name: Derek M. Frank
title: Derek M. Frank
permalink: pretty

timezone: America/Los_Angeles

google_analytics: UA-39564024-2

markdown: kramdown
theme: jekyll-theme-hacker
gems:
    - jekyll-coffescript
    - jekyll-paginate
    - jekyll-watch
    - jekyll-sitemap
    - jekyll-seo-tag

# External links
bitbucket: deerex
linkedin: derekmfrank
instagram: __dmf__
goodreads: dmfrank
lastfm: derekmfrank
facebook: derekmfrank
googleplus: 110520366075871893334
